SUBMISSIONS_FILENAME = './submissions.txt'
SOLUTIONS_DIRNAME = './solutions'
RESULTS_DIRNAME = './results'
NUMBER_OF_WINNERS = 3
NUM_PROBLEMS = 6
DEFAULT_SCORES = [1500, 1500, 1500, 1500, 1500, 1500]
DEFAULT_CORRECTNESS = [False, False, False, False, False, False]
SOLUTIONS = ['./answers/1.txt', './answers/2.txt', './answers/3.txt', './answers/4.txt', './answers/5.txt', './answers/6.txt']
SORT_ANSWERS = [False, False, True, False, False, False]